title: Florian Steitz
description: > # this means to ignore newlines until "baseurl:"
  Writing about software development, programming languages, and other technology
  topics. This site provides small tools, tutorials and showcases technologies.

# Endpoint
url: "http://www.steitz.online"
baseurl: ""

plugins:
- jekyll-last-modified-at
- jekyll-sitemap

theme: jekyll-theme-midnight