title: Florian Steitz
description: > # this means to ignore newlines until "baseurl:"
  Writing about software development, programming languages, and other technology
  topics. This site provides small tools, tutorials and showcases technologies.

# Endpoint
url: "http://www.steitz.online"
baseurl: ""

# Exclusions
exclude: [
  # Files
  Gemfile,
  Gemfile.lock,
  LICENSE.md,
  README.md,
]

plugins:
- jekyll-last-modified-at
- jekyll-sitemap

theme: jekyll-theme-midnight
google_analytics_id: UA-92535396-2
linkedin_url: https://www.linkedin.com/in/florian-steitz-2242aa6b
xing_url: https://www.xing.com/profile/Florian_Steitz2