title: Florian Steitz
description: > # this means to ignore newlines until "baseurl:"
  Software Architect Florian Steitz writes about software development, programming
  languages, IT and technology in general. He provides tools and tutorials.

# Endpoint
url: "http://www.steitz.online"
baseurl: ""

theme: jekyll-theme-midnight